name: Daily CI

on:
  # Retest daily to catch kernel breakage ASAP
  schedule:
    - cron: '0 4 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fedora-42:
    runs-on: ubuntu-24.04
    name: Fedora 42
    container: fedora:42
    steps:
      - uses: actions/checkout@v4
      - name: Build DAHDI and Asterisk
        run: |
          ./phreaknet.sh make
          GIT_REPO_PATH=${GITHUB_WORKSPACE} phreaknet install --fast --dahdi --autokvers --drivers --devmode --sip
  fedora-42-master:
    runs-on: ubuntu-24.04
    name: Fedora 42 Master
    container: fedora:42
    steps:
      - uses: actions/checkout@v4
      - name: Build DAHDI and Asterisk
        run: |
          ./phreaknet.sh make
          GIT_REPO_PATH=${GITHUB_WORKSPACE} phreaknet install --fast --dahdi --autokvers --drivers --devmode --sip --version=master
