name: Daily CI

on:
  # Retest daily to catch kernel breakage ASAP
  schedule:
    - cron: '0 4 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu-latest:
    runs-on: ubuntu-24.04
    name: Ubuntu 24.04
    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Build DAHDI and Asterisk
       run: |
          sudo ./phreaknet.sh make
          sudo GIT_REPO_PATH=${{ github.workspace }} phreaknet install --fast --dahdi --drivers --devmode --sip
